package com.accountbook.myaccountbook.domain;

public enum ExpenseCategory {
    GROCERY, EAT_OUT, DELIVERY, DAILY_NECESSITY, HOME_APPLIANCES, ELECTRONIC_PRODUCTS, CLOTHES, MEDICAL,
    PHONE, TRANSPORTATION, ENTERTAINMENT, PET, DEPOSIT, RENT, UTILITIES, REPAYMENT, TRIBUTE, ETC
}
