spring:
  profiles:
    active: local

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finance_schema?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: wjdehddnr1@

  redis:
    host: localhost
    port: 6379
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

accountHistory:
  scheduler:
    cron: "0 16 17 4 * ?"

---
spring:
  config:
    activate:
      on-profile: aws

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://18.234.31.176:3306/finance_schema?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: wjdehddnr1@

  redis:
    host: 18.234.31.176
    port: 6379
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

accountHistory:
  scheduler:
    cron: "10 0 0 1 * ?"